app:
  build: .
  ports:
    - 8080:8080
  volumes:
    - ./docs:/opt/app/docs
    - ./package.json:/opt/app/package.json
    - ./yarn.lock:/opt/app/yarn.lock
  container_name: komodo_docs
  stdin_open: true

