name: Build and Deploy doc sites
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"
          persist-credentials: false

      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository_owner }}/AtomicDEX-docs
          path: AtomicDEX-docs
          persist-credentials: false

      - name: Increase nodejs allowed memory
        run: export NODE_OPTIONS="--max-old-space-size=5120"

      - name: Build and Deploy to gh_pages
        uses: KomodoPlatform/vuepress-deploy@1.0.1
        env:
          ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
          ALGOLIAKEY: ${{secrets.ALGOLIA_SECRET}}
          TARGET_REPO: ${{ github.repository }}
          TARGET_BRANCH: gh-pages
          CNAME: "docs.komodoplatform.com"
          BUILD_SCRIPT: yarn && yarn docs:build
          BUILD_DIR: docs/.vuepress/dist/
